{{- if .Values.linkerd.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.linkerd.header }}
  labels:
    {{- include ".Chart.Name.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "{{ .Values.linkerd.host }}"
---
{{- end }}

{{- range $middleware := .Values.middlewares }}
{{ toYaml $middleware }}
---
{{- end }}
