{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include ".Chart.Name.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    client-id: "{{ .Values.clientId | quote }}"
  {{- end }}
{{- end }}  
