apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    {{- include ".Chart.Name.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template ".Chart.Name" . }}
    release: {{ .Release.Name }}
