{{- if or (eq .Values.environment "dev") (eq .Values.environment "tt02") }}
apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  name: {{ .Values.ingressRoute.name }}
  namespace: monitoring
  labels:
    pyrra.dev/team: {{ .Values.team }}
    pyrra.dev/app: {{ .Values.appName }}
    release: kube-prometheus-stack
    role: alert-rules
spec:
  indicator:
    ratio:
      errors:
        metric: traefik_service_requests_total{service=~".*{{ .Values.ingressRoute.name }}.*",code=~"5.."}
      total:
        metric: traefik_service_requests_total{service=~".*{{ .Values.ingressRoute.name }}.*"}
  target: {{ .Values.slo.target }}
  window: 4w
{{- end }}
