apiVersion: v2
type: application
version: 2.10.0
name: traefik-crds
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
description: |
  A Helm chart that deploy custom resource definitions (CRDs) for traefik.
keywords:
- traefik
- crds
appVersion: 2.10.0
