replicaCount: 2

environment: development

autoscaling:
  enabled: true
  replicas:
    min: 2
    max: 6
  avgCpuUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60

resources:
  requests:
    cpu: 200m
    memory: 256Mi

image:
  # Set "repository" name of your image for manual Helm install and upgrade.
  repository: browserless/chrome
  tag: 1-puppeteer-21.4.1
  pullPolicy: IfNotPresent

service:
  name: pdf-generator
  type: ClusterIP
  externalPort: 80
  # If your application is running on another port, change only the internal port.
  internalPort: 3000

startup:
  enabled: true
  path: "/metrics"

liveness:
  enabled: true
  path: "/metrics"

readiness:
  enabled: true
  path: "/metrics"
