replicaCount: 2

autoscaling:
  enabled: true
  replicas:
    min: 2
    max: 6
  avgCpuUtilization: 75
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60

resources:
  requests:
    cpu: 50m
    memory: 256Mi

podAnnotations: {}
  # Additional pod annotations (e.g. for mesh injection)
  # Enabling of linkerd in seperate value under
  # config.linkerd.io/proxy-cpu-request: 10m
  # config.linkerd.io/proxy-memory-limit: 250Mi
  # config.linkerd.io/proxy-memory-request: 20Mi

podAntiAffinity:
  enabled: true

image:
  # Set "repository" name of your image for manual Helm install and upgrade.
  repository:
  tag: latest
  pullPolicy: Always
  pullSecrets: []
  # - name: myRegistryKeySecretName

service:
  name: deployment
  type: ClusterIP
  externalPort: 80
  # If your application is running on another port, change only the internal port.
  internalPort: 5005

linkerd:
    enabled: true

ingressRoute:
  name: Will be inserted during deploy
  entryPoints:
    - http
    - https
  routes:
    - match: Will be inserted during deploy
      kind: Rule
      services:
        - name: Will be inserted during deploy
          port: 80
      middlewares:
        - name: hsts-header
  tls:
    options:
      name: tls-options
    secretName: ssl-cert

volumeMounts:
  - name: datakeys
    mountPath: /mnt/keys
  - name: accesstoken
    mountPath: "/accesstoken"

volumes:
  - name : datakeys
    persistentVolumeClaim:
      claimName: keys
  - name: accesstoken
    secret:
      secretName: accesstoken

startup:
  enabled: false
  path: /health
  failureThreshold: 3
  periodSeconds: 10
  timeoutSeconds: 1
readiness:
  enabled: false
  path: /health
  initialDelaySeconds: 30
  failureThreshold: 3
  periodSeconds: 3
  timeoutSeconds: 30
liveness:
  enabled: false
  path: /health
  initialDelaySeconds: 3
  failureThreshold: 3
  periodSeconds: 10
  timeoutSeconds: 30
