kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["pdf"]
    verbs: ["post", "get", "list"]
