apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "deploymentname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.linkerd.enabled }}
        linkerd.io/inject: enabled
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        config.linkerd.io/skip-outbound-ports: "443"
        {{- end }}
    spec:
    {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range $secret := .Values.image.pullSecrets }}
        - name : {{ $secret.name }}
      {{- end }}
    {{- end }}
    {{- if .Values.podAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "fullname" . }}
              topologyKey: kubernetes.io/hostname
            weight: 100
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ required "A valid image.repository value is required!" .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.image.environment}}
          {{- range $environment := .Values.image.environment}}
            - name: {{ $environment.name }}
              value: {{ quote $environment.value }}
          {{- end }}
          {{- end }}
            - name: ALTINN_KEYS_DIRECTORY
              value: "/mnt/keys"
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            {{- if .Values.resources.limits }}
            limits:
              {{- if .Values.resources.limits.cpu }}
              cpu: {{ .Values.resources.limits.cpu }}
              {{- end }}
              {{- if .Values.resources.limits.memory }}
              memory: {{ .Values.resources.limits.memory }}
              {{- end }}
            {{- end }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            allowPrivilegeEscalation: false
          {{- if .Values.volumeMounts}}
          volumeMounts:
            {{- range $mount := .Values.volumeMounts}}
            - name: {{ $mount.name }}
              mountPath: {{ $mount.mountPath }}
            {{- end }}
          {{- end }}
          {{- if .Values.startup.enabled}}
          startupProbe:
            httpGet:
              path: {{ .Values.startup.path }}
              port: {{ .Values.service.internalPort }}
            failureThreshold: {{ .Values.startup.failureThreshold }}
            periodSeconds: {{ .Values.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.startup.timeoutSeconds }}
          {{- end }}
          {{- if .Values.readiness.enabled}}
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.path }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.readiness.initialDelaySeconds }}
            failureThreshold: {{ .Values.readiness.failureThreshold }}
            periodSeconds: {{ .Values.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.readiness.timeoutSeconds }}
          {{- end }}
          {{- if .Values.liveness.enabled}}
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.path }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.liveness.initialDelaySeconds }}
            failureThreshold: {{ .Values.liveness.failureThreshold }}
            periodSeconds: {{ .Values.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.liveness.timeoutSeconds }}
          {{- end }}
      volumes:
        {{- range $volume := .Values.volumes }}
          - name: {{ $volume.name }}
            {{- if $volume.persistentVolumeClaim }}
            persistentVolumeClaim:
              claimName: {{ $volume.persistentVolumeClaim.claimName }}
            {{- end }}
            {{- if $volume.secret }}
            secret:
              secretName: {{ $volume.secret.secretName }}
            {{- end }}
        {{- end }}
