{{- if .Values.linkerd.enabled }}
---
apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}
  port: http
  proxyProtocol: HTTP/1
  accessPolicy: all-unauthenticated
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  server:
    name: {{ template "fullname" . }}
  client:
    meshTLS:
      identities:
        - "*"
{{- end }}
