{{- if .Values.linkerd.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ template "fullname" . }}
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: {{ printf "%s.default.svc.cluster.local:80" (include "fullname" .) }}
---
{{- end }}

{{- range $middleware := .Values.middlewares }}
{{ toYaml $middleware }}
---
{{- end }}
